Changes in QtChineseChessGame
LDY1998/QtChineseChessGame pull request #3
Opened 2020-09-10 13:09 UTC by Rickson2019

Annotation & new code

2020-09-10 14:48 UTC, LDY1998 commented on QtChineseChessGame/QtChineseChessGame.h
> +	void startGame(QtChineseChessGame *game = Q_NULLPTR, Board *board = Q_NULLPTR);
How come a function of QtChineseChessGame will need to pass itself into a function? I guess you can you this(https://www.runoob.com/cplusplus/cpp-this-pointer.html) to do the job

2020-09-10 14:51 UTC, LDY1998 commented on QtChineseChessGame/Board.cpp
> +class QtChineseChessGame;
I would like to try differnet approach here, maybe we initialize the game as the parent of board and then cast it into the right pointer, that can make things easier instead of manually declare the class here.

2020-09-10 14:52 UTC, LDY1998 commented on QtChineseChessGame/ChessPiece.cpp
>  ChessPiece::~ChessPiece()
Maybe we need to remove this destructor and let the default one handle the job as we extend the QLabel class

2020-09-10 15:02 UTC, LDY1998 requested changes
First thing is that we might want some decoupling between board and chinese chess game, as the game should be the parent widget of board.

Second, as we have multiple game mode in the future, we should consider the extension issue. I suggest we have a base game class and have PVP game mode extend it, then we use all of your logic

Third, we should consider how swap turn will disable one player's mouse event (forbid the player to move any of opposite side of chess), forgive if I miss that part and you already get that done.

2020-09-12 13:40 UTC, Rickson2019 commented on QtChineseChessGame/Board.cpp
> +class QtChineseChessGame;
I thought a board is part of a "game".
Here is my thoughts:
In one chess game, there is a chessboard, there are pieces on the board ( written in the board class).
Then you have players who play the game, which can be members of a "game" and you will have a set of rules like timing and score record that can be tracked by attributes in the "game" as well.

2020-09-12 16:32 UTC, merged